config/routes.rb
# Rails.application.routes.draw do
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

#   root to: "home#index"
# end





require 'sidekiq'
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq ----------------------------------------------------------
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'admin'
  end
  mount Sidekiq::Web => '/sidekiq'




  # CRUD Operations -------------------------------------------------
  namespace 'crud' do
    resources :diaries, controller: 'diaries_crud'    
  end

  # get '/diaries/', to: 'crud/diaries_crud#index'
  # get '/diaries/new', to: 'crud/diaries_crud#new'
  # get '/diaries/:id', to: 'crud/diaries_crud#show'
  # get '/diaries/:id/edit', to: 'crud/diaries_crud#edit'

  #post '/diaries/', to: 'crud/diaries_crud#create'
  #delete '/diaries/:id', to: 'crud/diaries_crud#destroy'


  #   $ bin/rails routes
  #       Prefix Verb   URI Pattern                  Controller#Action
  #         root GET    /                            articles#index
  #     articles GET    /articles(.:format)          articles#index
  #  new_article GET    /articles/new(.:format)      articles#new
  #      article GET    /articles/:id(.:format)      articles#show
  #              POST   /articles(.:format)          articles#create
  # edit_article GET    /articles/:id/edit(.:format) articles#edit
  #              PATCH  /articles/:id(.:format)      articles#update
  #              DELETE /articles/:id(.:format)      articles#destroy




  # API --------------------------------------------------------------
  namespace 'api' do
    namespace 'v1' do
      resources :diaries, controller: 'diaries_api'
      resources :notes, controller: 'notes_api'
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  has_many :notes, dependent: :delete_all
  validates :title, presence: true
  validates :expiration, presence: true

  enum kind: {
    for_all: 2,
    personal: 1
  }
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :diary
  validates_associated :diary

  validates :text, presence: true, length: { in: 5..300 }
  validates :diary_id, presence: true
end

app/controllers/api/v1/diaries_api_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Main class for Dictionaries API
    class DiariesApiController < ApplicationController
      def index
        diaries = Diary.order('created_at DESC')
        render json: { status: 'SUCCESS', message: 'Loaded diaries', data: diaries }, status: :ok
      end

      def show
        diary = Diary.find(params[:id])
        render json: { status: 'SUCCESS', message: 'Loaded diary', data: diary }, status: :ok
      end

      def create
        diary = Diary.new(diary_params)

        if diary.save
          render json: { status: 'SUCCESS', message: 'Saved diary', data: diary }, status: :ok
        else
          render json: { status: 'ERROR', message: 'Diary not saved', data: diary.errors },
                 status: :unprocessable_entity
        end
      end

      def destroy
        diary = Diary.find(params[:id])
        diary.destroy
        render json: { status: 'SUCCESS', message: 'Deleted diary', data: diary }, status: :ok
      end

      def update
        diary = Diary.find(params[:id])
        if diary.update_attributes(diary_params)
          render json: { status: 'SUCCESS', message: 'Updated diary', data: diary }, status: :ok
        else
          render json: { status: 'ERROR', message: 'Diary not updated', data: diary.errors },
                 status: :unprocessable_entity
        end
      end

      private

      def diary_params
        params.permit(:title, :expiration, :kind)
      end
    end
  end
end

app/controllers/api/v1/notes_api_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Main class for Notes API
    class NotesApiController < ApplicationController
      def index
        notes = Note.order('created_at DESC')
        render json: { status: 'SUCCESS', message: 'Loaded notes', data: notes }, status: :ok
      end

      def show
        note = Note.find(params[:id])
        render json: { status: 'SUCCESS', message: 'Loaded note', data: note }, status: :ok
      end

      def create
        note = Note.new(note_params)

        if note.save
          render json: { status: 'SUCCESS', message: 'Saved note', data: note }, status: :ok
        else
          render json: { status: 'ERROR', message: 'Note not saved', data: note.errors }, status: :unprocessable_entity
        end
      end

      def destroy
        note = Note.find(params[:id])
        note.destroy
        render json: { status: 'SUCCESS', message: 'Deleted note', data: note }, status: :ok
      end

      def update
        note = Note.find(params[:id])
        if note.update_attributes(note_params)
          render json: { status: 'SUCCESS', message: 'Updated note', data: note }, status: :ok
        else
          render json: { status: 'ERROR', message: 'Note not updated', data: note.errors },
                 status: :unprocessable_entity
        end
      end

      private

      def note_params
        params.permit(:text, :diary_id)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crud/diaries_crud_controller.rb
module Crud
  class DiariesCrudController < ApplicationController
    def index
      @diaries = Diary.all
    end

    def show
      @diaries = Diary.find(params[:id])
    end

    def new
      @diary = Diary.new
    end

    def create
      @diary = Diary.new(diary_params)

      if @diary.save
        redirect_to controller: 'diaries_crud', action: 'index'
      else
        render :new
      end
    end

    def edit
      @diary = Diary.find(params[:id])
    end

    def update
      @diary = Diary.find(params[:id])

      if @diary.update(diary_params)
        redirect_to controller: 'diaries_crud', action: 'index'
      else
        render :edit
      end
    end

    def destroy
      @diary = Article.find(params[:id])
      @diary.destroy

      redirect_to root_path
    end

    private

    def diary_params
      params.require(:diary).permit(:title, :expiration, :kind)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crud_helper.rb
# frozen_string_literal: true

module CrudHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/crud/diaries_crud/_form.html.erb
<%= form_with model: diary, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%= diary.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :expiration %><br>
    <%= form.text_field :expiration %>
    <%= diary.errors.full_messages_for(:expiration).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <%= form.label :kind %><br>
  <%= form.text_field :kind %>
  <%= diary.errors.full_messages_for(:kind).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/crud/diaries_crud/edit.html.erb
<h1>Edit Diary</h1>

<%= render "form", diary: @diary %>

app/views/crud/diaries_crud/index.html.erb
<section class='main_section'>
  <div class='wrapper'>

    <div class="main_section_header">
      <h1>Diaries</h1>

      <a href="/diaries/new/" class="create_new">Create new diary</a>
    </div>

    <ul>
      <% @diaries.each do |diary| %>
        <li>
          <%= link_to diary.title, new_crud_diary_path(@diaries.ids) %>
        </li>
    
        <br>
      <% end %>
    </ul>

  </div>
</section>



<h1>List of diaries</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @diaries.each do |diary| %>
    <tr>
      <td><%= link_to diary.title, @diary %></td>

        
    </tr>
  <% end -%>
</table>

app/views/crud/diaries_crud/new.html.erb
<h1>New Diary</h1>

<%= form_with model: @diary, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :expiration %><br>
    <%= form.text_area :expiration %>
  </div>

  <div>
    <%= form.label :kind %><br>
    <%= form.text_area :kind %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/crud/diaries_crud/show.html.erb
<h1><a href="/diaries/">Home</a></h1>

<h3><%= @diaries.title %></h3>

<p><%= @diaries.expiration %></p>
<p><%= @diaries.kind %></p>

<h3><a href="/diaries/<%= @diaries.id %>/edit">Edit</a></h3>
<%= link_to 'Edit', edit_crud_diary_path(@diaries.id) %>

app/views/home/index.html.erb
<h1>hjkolpkjhbjikoj</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJuniorApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>